# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieHDDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MovieHDDemo
pod ‘AFNetworking’
pod ‘JSONModel’
pod ‘ReactiveObjC’
pod 'SVProgressHUD'
end
